version: '2'

volumes:
  nginxdata: {}

services:
  nginx:
    image: nginx:latest
    mem_limit: 20000000
    ports:
      - "8080:80"
    volumes:
      - nginxdata:/usr/share/nginx/html/:ro
  instance-id-getter:
    image: busybox:latest
    mem_limit: 10000000
    environment:
      - MYVAR=${MYVAR}
    volumes:
      - nginxdata:/nginx
    command: sh -c "while true; do echo \"Hello world <p><pre> `env` </pre></p> \" > /nginx/index.html; sleep 3; done"
